- 넣어줘야 할 데이터: metadata > action | metadata > annotations
- 정답지가 될 데이터: metadata > action | metadata > inspect > emotion

In [1]:
import pandas as pd
import json
import os

In [2]:
path = 'C:/Users/admin/Desktop/PetProject/20201028_cat-arch-000156.mp4'

In [3]:
jpgtitle = os.listdir(path)
print(jpgtitle)

['frame_0_timestamp_0.jpg', 'frame_102_timestamp_6800.jpg', 'frame_105_timestamp_7000.jpg', 'frame_108_timestamp_7200.jpg', 'frame_111_timestamp_7400.jpg', 'frame_114_timestamp_7600.jpg', 'frame_117_timestamp_7800.jpg', 'frame_120_timestamp_8000.jpg', 'frame_123_timestamp_8200.jpg', 'frame_126_timestamp_8400.jpg', 'frame_129_timestamp_8600.jpg', 'frame_12_timestamp_800.jpg', 'frame_132_timestamp_8800.jpg', 'frame_135_timestamp_9000.jpg', 'frame_138_timestamp_9200.jpg', 'frame_141_timestamp_9400.jpg', 'frame_144_timestamp_9600.jpg', 'frame_147_timestamp_9800.jpg', 'frame_150_timestamp_10000.jpg', 'frame_153_timestamp_10200.jpg', 'frame_156_timestamp_10400.jpg', 'frame_159_timestamp_10600.jpg', 'frame_15_timestamp_1000.jpg', 'frame_162_timestamp_10800.jpg', 'frame_165_timestamp_11000.jpg']

In [4]:
with open('20201028_cat-arch-000156.mp4.json', encoding='utf-8') as jsonfile:
    data = json.load(jsonfile)
df = pd.json_normalize(data['annotations'])
df = df.drop(columns=['frame_number', 'frame_url', 'timestamp'])
df

,keypoints.1.x,keypoints.1.y,keypoints.2.x,keypoints.2.y,keypoints.3,keypoints.4,keypoints.5,keypoints.6.x,keypoints.6.y,keypoints.7.x,...,keypoints.6,keypoints.5.x,keypoints.5.y,keypoints.1,keypoints.12,keypoints.7,keypoints.2,keypoints.8,keypoints.9,keypoints.13
0,563.0,600.0,553.0,503.0,NaN,NaN,NaN,501.0,635.0,619.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,549.0,566.0,545.0,472.0,NaN,NaN,NaN,502.0,629.0,619.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,544.0,526.0,542.0,450.0,NaN,NaN,NaN,503.0,619.0,622.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,548.0,525.0,545.0,450.0,NaN,NaN,NaN,503.0,619.0,614.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,551.0,528.0,548.0,450.0,NaN,NaN,NaN,506.0,619.0,616.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,750.0,994.0,717.0,876.0,NaN,NaN,NaN,NaN,NaN,858.0,...,NaN,754.0,751.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76,753.0,974.0,727.0,858.0,NaN,NaN,NaN,NaN,NaN,879.0,...,NaN,776.0,735.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
77,733.0,970.0,713.0,852.0,NaN,NaN,NaN,NaN,NaN,853.0,...,NaN,776.0,735.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78,692.0,966.0,677.0,843.0,NaN,NaN,NaN,NaN,NaN,853.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79,632.0,940.0,620.0,817.0,NaN,NaN,NaN,NaN,NaN,803.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df.columns

Index(['keypoints.1.x', 'keypoints.1.y', 'keypoints.2.x', 'keypoints.2.y',
       'keypoints.3', 'keypoints.4', 'keypoints.5', 'keypoints.6.x',
       'keypoints.6.y', 'keypoints.7.x', 'keypoints.7.y', 'keypoints.8.x',
       'keypoints.8.y', 'keypoints.9.x', 'keypoints.9.y', 'keypoints.10',
       'keypoints.11.x', 'keypoints.11.y', 'keypoints.12.x', 'keypoints.12.y',
       'keypoints.13.x', 'keypoints.13.y', 'keypoints.14.x', 'keypoints.14.y',
       'keypoints.15.x', 'keypoints.15.y', 'bounding_box.x', 'bounding_box.y',
       'bounding_box.width', 'bounding_box.height', 'keypoints.3.x',
       'keypoints.3.y', 'keypoints.4.x', 'keypoints.4.y', 'keypoints.6',
       'keypoints.5.x', 'keypoints.5.y', 'keypoints.1', 'keypoints.12',
       'keypoints.7', 'keypoints.2', 'keypoints.8', 'keypoints.9',
       'keypoints.13'],
      dtype='object')

In [5]:
# 반복문으로 프레임당 메모장 하나씩 저장하기 테스트 코드
# 오류메세지가 뜨지만 제대로 작동하는 것을 확인했다
for i in range(len(df)):
    rowdf = df.iloc[i, :]
    rowdf.reset_index(drop=True)
    rowdf.to_csv(f'{jpgtitle[i]}.txt')

IndexError: list index out of range